name: 04 - Secrets and Env
on: [push]

env:
  GLOBAL_ENV: "available-to-all-jobs"

jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "available-to-this-job-only"
    steps:
      - run: |
         echo "Global: $GLOBAL_ENV"
      - run: |
         echo "Job-level: $JOB_ENV"
      - name: Use a secret safely
        run: echo "Secret is set, length check only"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - run: |
         if [ -z "$MY_SECRET" ]; then echo "NOT SET"; else echo "SECRET IS SET"; fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
